version: 2.1

orbs:
  maven: archmix/maven@2

workflows:
  version: 2
  build-deploy:
    jobs:
      - maven/build:
          name: build
          setup_remote_docker: true
          context: Archmix
      - maven/release:
          context: Archmix
          requires:
            - build
          filters:
            branches:
              only: master
